### ISSUE TITLE
不知道为啥,我运行完没有生效,代码也执行完毕了  python3.8

### ISSUE THREAD

**Issue by lvkaixuan** [beiyuouo/generate-big-watermelon-image#1]

**Comment by yyyanbj** [comment]
emmm，控制台没有什么输出提示吗？

**Comment by lvkaixuan** [comment]
没有任何报错,而且代码完整的执行完了... 就是文件没有被替换

**Comment by yyyanbj** [comment]
如果是正常执行完毕是会输出被替换的图片的，如果没有任何输出的话那确实不太正常0.0

**Comment by yyyanbj** [comment]
可以截图下控制台吗-，-

**Comment by lvkaixuan** [comment]
不知是否跟上面这个提示有关 截图链接: https://img04.sogoucdn.com/app/a/100520146/54a0b6332245a6b8770c3a8421cb66bf

**Comment by yyyanbj** [comment]
因为我用的OpenCV的版本是4.5.0，你可以通过`print(cv.__version__)`来查看OpenCV版本，如果跨了一个大版本号建议更新一下0.0

**Comment by yyyanbj** [comment]
感觉你这个应该是替换成功了呀..图片会直接输出到`game\res\raw-assets`里面对应的文件夹中，你可以打开`50`这个文件夹，里面应该放的是`11.jpeg`对应的图片

**Comment by lvkaixuan** [comment]
我知道什么问题了,我用的是Mac路径和Windows不一样
https://img03.sogoucdn.com/app/a/100520146/c65e457c19ebec58b379a904ad634c33

**Comment by yyyanbj** [comment]
87750309e178457aea7e6d53fcbb6673c7f0e177
sorry，之前确实没考虑这个问题，一般我都是windows开发0.0，用`os.path`可以解决路径问题，已修复
